- name: Create jobs - "{{item.dir}}/{{item.name}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/templates/job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.85.152:8080
    user: admin
    password: "{{jenkins_password}}"

