- name: create config file
  ansible.builtin.template:
    src: s-s-job.xml
    dest: /tmp/s-job.xml

- name: Create jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.85.152:8080
    user: admin
    password: "{{jenkins_password}}"

